
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 08 23:31:10 CST 2020
//----------------------------------------------------

package com.polloenpelotas.AnalizadorCup;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int doo = 49;
  public static final int function = 37;
  public static final int mayorQue = 10;
  public static final int igualQue = 8;
  public static final int alla = 26;
  public static final int cbra = 24;
  public static final int falsee = 32;
  public static final int switchh = 45;
  public static final int difQue = 9;
  public static final int dividir = 5;
  public static final int coma = 25;
  public static final int igual = 22;
  public static final int abra = 23;
  public static final int identifier = 30;
  public static final int abra2 = 35;
  public static final int menorQue = 12;
  public static final int elsee = 43;
  public static final int nothing = 36;
  public static final int potenciar = 6;
  public static final int casee = 46;
  public static final int pComa = 21;
  public static final int numero = 28;
  public static final int returnn = 41;
  public static final int menos = 3;
  public static final int iff = 42;
  public static final int truee = 31;
  public static final int EOF = 0;
  public static final int dosp = 18;
  public static final int mas = 2;
  public static final int whilee = 48;
  public static final int error = 1;
  public static final int breakk = 44;
  public static final int tern = 17;
  public static final int arrow = 38;
  public static final int or = 15;
  public static final int por = 4;
  public static final int defaultt = 40;
  public static final int mayorIgualQue = 11;
  public static final int invokeFun = 39;
  public static final int and = 14;
  public static final int cpar = 20;
  public static final int not = 16;
  public static final int umenos = 34;
  public static final int continuee = 47;
  public static final int clla = 27;
  public static final int modulo = 7;
  public static final int decimal = 29;
  public static final int cadena = 33;
  public static final int apar = 19;
  public static final int menorIgualQue = 13;
}

