
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 21 13:34:43 CST 2020
//----------------------------------------------------

package com.polloenpelotas.AnalizadorCup;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int mayorIgualQue = 11;
  public static final int dosp = 18;
  public static final int cadena = 28;
  public static final int igualQue = 8;
  public static final int print = 30;
  public static final int identifier = 25;
  public static final int decimal = 24;
  public static final int menorIgualQue = 13;
  public static final int not = 16;
  public static final int numero = 23;
  public static final int falsee = 27;
  public static final int cpar = 20;
  public static final int por = 4;
  public static final int or = 15;
  public static final int menos = 3;
  public static final int truee = 26;
  public static final int pComa = 21;
  public static final int igual = 22;
  public static final int EOF = 0;
  public static final int tern = 17;
  public static final int difQue = 9;
  public static final int error = 1;
  public static final int umenos = 29;
  public static final int mas = 2;
  public static final int modulo = 7;
  public static final int menorQue = 12;
  public static final int potenciar = 6;
  public static final int and = 14;
  public static final int apar = 19;
  public static final int dividir = 5;
  public static final int mayorQue = 10;
}

