/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de expresiones aritmeticas sencillas. */

package com.polloenpelotas.AnalizadorJCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 5;
  /** RegularExpression Id. */
  int DECIMAL = 6;
  /** RegularExpression Id. */
  int PRINT = 7;
  /** RegularExpression Id. */
  int PCOMA = 8;
  /** RegularExpression Id. */
  int PARENI = 9;
  /** RegularExpression Id. */
  int PAREND = 10;
  /** RegularExpression Id. */
  int CORI = 11;
  /** RegularExpression Id. */
  int CORD = 12;
  /** RegularExpression Id. */
  int MAS = 13;
  /** RegularExpression Id. */
  int MENOS = 14;
  /** RegularExpression Id. */
  int POR = 15;
  /** RegularExpression Id. */
  int DIV = 16;
  /** RegularExpression Id. */
  int POT = 17;
  /** RegularExpression Id. */
  int MENORQUE = 18;
  /** RegularExpression Id. */
  int MAYORQUE = 19;
  /** RegularExpression Id. */
  int MENORIGUAL = 20;
  /** RegularExpression Id. */
  int MAYORIGUAL = 21;
  /** RegularExpression Id. */
  int IGUALACION = 22;
  /** RegularExpression Id. */
  int DIFERENCIACION = 23;
  /** RegularExpression Id. */
  int AND = 24;
  /** RegularExpression Id. */
  int OR = 25;
  /** RegularExpression Id. */
  int TRUE = 26;
  /** RegularExpression Id. */
  int FALSE = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<NUMERO>",
    "<DECIMAL>",
    "\"print\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&\"",
    "\"|\"",
    "\"true\"",
    "\"false\"",
  };

}
