/* Generated By:JavaCC: Do not edit this line. GramaticaConstants.java */
/** Analizador de expresiones aritmeticas sencillas. */

package com.polloenpelotas.AnalizadorJCC;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMERO = 7;
  /** RegularExpression Id. */
  int DECIMAL = 8;
  /** RegularExpression Id. */
  int PCOMA = 9;
  /** RegularExpression Id. */
  int APAR = 10;
  /** RegularExpression Id. */
  int CPAR = 11;
  /** RegularExpression Id. */
  int MAS = 12;
  /** RegularExpression Id. */
  int MENOS = 13;
  /** RegularExpression Id. */
  int POR = 14;
  /** RegularExpression Id. */
  int DIV = 15;
  /** RegularExpression Id. */
  int POT = 16;
  /** RegularExpression Id. */
  int MENORQUE = 17;
  /** RegularExpression Id. */
  int MAYORQUE = 18;
  /** RegularExpression Id. */
  int MENORIGUAL = 19;
  /** RegularExpression Id. */
  int MAYORIGUAL = 20;
  /** RegularExpression Id. */
  int IGUAL = 21;
  /** RegularExpression Id. */
  int ARROW = 22;
  /** RegularExpression Id. */
  int IGUALACION = 23;
  /** RegularExpression Id. */
  int DIFERENCIACION = 24;
  /** RegularExpression Id. */
  int AND = 25;
  /** RegularExpression Id. */
  int OR = 26;
  /** RegularExpression Id. */
  int NOT = 27;
  /** RegularExpression Id. */
  int MODULAR = 28;
  /** RegularExpression Id. */
  int ABRA = 29;
  /** RegularExpression Id. */
  int CBRA = 30;
  /** RegularExpression Id. */
  int TRUE = 31;
  /** RegularExpression Id. */
  int FALSE = 32;
  /** RegularExpression Id. */
  int COMA = 33;
  /** RegularExpression Id. */
  int ALLA = 34;
  /** RegularExpression Id. */
  int CLLA = 35;
  /** RegularExpression Id. */
  int TERN = 36;
  /** RegularExpression Id. */
  int DOSP = 37;
  /** RegularExpression Id. */
  int NOTHING = 38;
  /** RegularExpression Id. */
  int RETURN = 39;
  /** RegularExpression Id. */
  int FUNCTION = 40;
  /** RegularExpression Id. */
  int DEFAULTT = 41;
  /** RegularExpression Id. */
  int IF = 42;
  /** RegularExpression Id. */
  int ELSE = 43;
  /** RegularExpression Id. */
  int BREAK = 44;
  /** RegularExpression Id. */
  int SWITCH = 45;
  /** RegularExpression Id. */
  int CASE = 46;
  /** RegularExpression Id. */
  int WHILE = 47;
  /** RegularExpression Id. */
  int CONTINUE = 48;
  /** RegularExpression Id. */
  int DO = 49;
  /** RegularExpression Id. */
  int FOR = 50;
  /** RegularExpression Id. */
  int IN = 51;
  /** RegularExpression Id. */
  int IDENTIFIER = 52;
  /** RegularExpression Id. */
  int STRING = 55;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int STRING_STATE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<NUMERO>",
    "<DECIMAL>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"=>\"",
    "\"==\"",
    "\"!=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"%%\"",
    "\"[\"",
    "\"]\"",
    "\"true\"",
    "\"false\"",
    "\",\"",
    "\"{\"",
    "\"}\"",
    "\"?\"",
    "\":\"",
    "\"null\"",
    "\"return\"",
    "\"function\"",
    "\"default\"",
    "\"if\"",
    "\"else\"",
    "\"break\"",
    "\"switch\"",
    "\"case\"",
    "\"while\"",
    "\"continue\"",
    "\"do\"",
    "\"for\"",
    "\"in\"",
    "<IDENTIFIER>",
    "\"\\\"\"",
    "<token of kind 54>",
    "\"\\\"\"",
  };

}
